### ISSUE TITLE
Hi there :)

### ISSUE THREAD

**Issue by SourcingDenis** [p141592/linkedin_tricks#4]
Николай @p141592 , приветствую! Выглядит ну ооочень круто, не могу не поинтересоваться у тебя - как этим пользоваться?))) Спасибо тебе огромное за твое время. Cheers, Денис!

**Comment by p141592** [comment]
Привет, Денис)

Нужно зайти на страницу https://www.linkedin.com/mynetwork/
Открываешь консоль браузера, копируешь туда код из https://github.com/p141592/linkedin_tricks/blob/master/mynetwork_expansion.js

Нажимаешь enter и готово)

`get_statistic()` - Можно в любое время ввести в консоли, покажется статистика работы скрипта

**Comment by SourcingDenis** [comment]
А какие у этого скрипта стоят ограничения?

**Comment by p141592** [comment]
Ограничений никаких нет, есть фильтр. 

Если позиция пользователя совпадает со следующими или _есть это слово в позиции_, то пользователь добавляется в друзья.
```javascript
const PASS_POSITIONS = [
    'recruitment', 'recruiter', 'hr', 'recruiting', 'head', 'lead',
    'cio', 'cto', 'founder', 'talents', 'talent', 'hunter', 'hiring',
    'chief'
];
```

Для всех остальных условие: _Количество общих друзей должно быть меньше этого числа_
```javascript
const max_MUTUAL_FIENDS = 30;
```
Скрипт частенько выпадает из работы. Из-за недоработок или каких-то блокировок. Я его запускаю каждый день, исправляю баги, меняю интервал приглашений и тому подобное, чтобы он мог крутиться вечно на каком-нибудь `raspberrypi`

Текущая версия `1.0` - не очень стабильна, пока запускал ее только раз 6

Скрипт можно остановить командой - `stop()`
Запустить - `start()`, если он вдруг остановился по непонятной причине

**Comment by p141592** [comment]
На текущий момент - лучший результат новой версии на одном запуске:
`602` - Приглашения
`1235` - Пропарсенных контакта
`134` - Цикла

**Comment by SourcingDenis** [comment]
спасибо большое!
