### ISSUE TITLE
Новая фича

### ISSUE THREAD

**Issue by baimurzin** [p141592/linkedin_tricks#5]
company_grab.js - это будет новая фича по сбору компаний из linkedin?

**Comment by p141592** [comment]
Я хочу сделать скрипт, который будет приглашать людей из списка определенных компаний. Захожу на страницу компании, пролистываю список всех людей, добавляю по совпавшим позициям, пишу invite сообщение. 

Чтобы можно было к примеру связаться со всеми hr компании. Или написать что-то всем разработчикам компании и так далее.

**Comment by baimurzin** [comment]
@p141592  Аа, ну тоже полезный скрипт, но спарсить все существующие компании зарегистрированные на linkedin было бы неплохо. Не знаешь есть ли такая возможность?

**Comment by p141592** [comment]
Не знаю, не думал на этот счет. Не понятно просто как это использовать. Не думал делать что-то подобное. Куда это может пригодиться?

**Comment by baimurzin** [comment]
Можно разбивать компании по групппам: по виду деятельности(ИТ, нефть и газ, финансы), по размеру компании(1-10, 10-100, 100-500 человек) и тд. Делать анализ рынка и например делать опросы или рассылки, ну вообщем применения найти можно

**Comment by p141592** [comment]
Проблема в том, что в консоли браузера нельзя передавать информацию на хранения куда-то на другой ресурс. И вообще взаимодействие со сторонними ресурсами в браузере скорее всего будет запрещено политикой безопасности самого браузера. Это нужно писать и исполнять какой-то скрипт на стороне сервера, чтобы результаты можно было хранить.

@baimurzin Если сможешь описать - чего нужно получить, я поделаю в свободное время. На Python напишу парсер. В целом это вполне реалистичная задача.
